---
driver:
  name: vagrant
  use_sudo: false
  customize:
    memory: 4096
    cpus: 2

provisioner:
  product_name: chef
  #product_version: 14.1.12

platforms:
  - name: ubuntu-18.04
  - name: centos-7.5

suites:
  - name: default
    run_list:
      - recipe[pio::aio]
    attributes:
      pio:
        provision_only: true
