---
driver:
  name: vagrant
  use_sudo: false
  customize:
    memory: 3074
    cpus: 2

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04
  - name: centos-7.4

suites:
  - name: default
    run_list:
      - recipe[pio::aio]
    attributes:
      pio:
        service_manager: auto
        provision_only: true
