language: ruby
services: docker

stages:
  - name: deploy
    if: tag =~ ^v[0-9]

jobs:
  include:
    - 
      if: (branch = master) AND (type IN (pull_request))
      script:
        - cp -f .travis-kitchen.yml .kitchen.yml
        - travis_wait 30 bundle exec kitchen converge ubuntu-1604
        - bundle exec kitchen verify ubuntu-1604
    - stage: deploy
      script: |
        curl -s
          --header "Content-Type: application/json"
          --data "{\"build_parameters\": {\"release_tag\": \"$TRAVIS_TAG\"}}"
          --request POST $PUBLISH_URL > /dev/null
