---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04
    driver_config:
      image: ubuntu:18.04
      platform: ubuntu
      provision_command: apt-get -q install locales && locale-gen en_US.UTF-8
  - name: centos-7
    driver_config:
      image: centos:7
      platform: centos

suites:
  - name: travis
    run_list:
      - recipe[pio::aio]
    attributes:
      pio:
        service_manager: execute
        provision_only: false
